// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Back: typeof import("./src/components/layout/header/src/back.vue")["default"];
    Control: typeof import("./src/components/layout/footer/src/control.vue")["default"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElCarousel: typeof import("element-plus/es")["ElCarousel"];
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSlider: typeof import("element-plus/es")["ElSlider"];
    Header: typeof import("./src/components/layout/header/src/header.vue")["default"];
    IconPart: typeof import("./src/components/icon/iconPart.vue")["default"];
    MenuButton: typeof import("./src/components/layout/header/src/menu-button.vue")["default"];
    PageMenu: typeof import("./src/components/layout/menu/src/page-menu.vue")["default"];
    PlayInfo: typeof import("./src/components/layout/footer/src/playInfo.vue")["default"];
    PlayList: typeof import("./src/components/layout/footer/src/playList.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Search: typeof import("./src/components/layout/header/src/search.vue")["default"];
    SearchInfo: typeof import("./src/components/layout/header/src/searchInfo.vue")["default"];
    SliderInput: typeof import("./src/components/layout/footer/src/sliderInput.vue")["default"];
    Src: typeof import("./src/components/layout/footer/src/index.vue")["default"];
    Volume: typeof import("./src/components/layout/footer/src/volume.vue")["default"];
  }
}

export {};
